/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoryRouteImport } from './routes/story'
import { Route as OrderRouteImport } from './routes/order'
import { Route as GiftRouteImport } from './routes/gift'
import { Route as FlavorsRouteImport } from './routes/flavors'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IndexOldRouteImport } from './routes/index.old'
import { Route as FlavorsSlugRouteImport } from './routes/flavors.$slug'

const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderRoute = OrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftRoute = GiftRouteImport.update({
  id: '/gift',
  path: '/gift',
  getParentRoute: () => rootRouteImport,
} as any)
const FlavorsRoute = FlavorsRouteImport.update({
  id: '/flavors',
  path: '/flavors',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexOldRoute = IndexOldRouteImport.update({
  id: '/index/old',
  path: '/index/old',
  getParentRoute: () => rootRouteImport,
} as any)
const FlavorsSlugRoute = FlavorsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => FlavorsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/flavors': typeof FlavorsRouteWithChildren
  '/gift': typeof GiftRoute
  '/order': typeof OrderRoute
  '/story': typeof StoryRoute
  '/flavors/$slug': typeof FlavorsSlugRoute
  '/index/old': typeof IndexOldRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/flavors': typeof FlavorsRouteWithChildren
  '/gift': typeof GiftRoute
  '/order': typeof OrderRoute
  '/story': typeof StoryRoute
  '/flavors/$slug': typeof FlavorsSlugRoute
  '/index/old': typeof IndexOldRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/flavors': typeof FlavorsRouteWithChildren
  '/gift': typeof GiftRoute
  '/order': typeof OrderRoute
  '/story': typeof StoryRoute
  '/flavors/$slug': typeof FlavorsSlugRoute
  '/index/old': typeof IndexOldRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/flavors'
    | '/gift'
    | '/order'
    | '/story'
    | '/flavors/$slug'
    | '/index/old'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/flavors'
    | '/gift'
    | '/order'
    | '/story'
    | '/flavors/$slug'
    | '/index/old'
  id:
    | '__root__'
    | '/'
    | '/flavors'
    | '/gift'
    | '/order'
    | '/story'
    | '/flavors/$slug'
    | '/index/old'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FlavorsRoute: typeof FlavorsRouteWithChildren
  GiftRoute: typeof GiftRoute
  OrderRoute: typeof OrderRoute
  StoryRoute: typeof StoryRoute
  IndexOldRoute: typeof IndexOldRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gift': {
      id: '/gift'
      path: '/gift'
      fullPath: '/gift'
      preLoaderRoute: typeof GiftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flavors': {
      id: '/flavors'
      path: '/flavors'
      fullPath: '/flavors'
      preLoaderRoute: typeof FlavorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/index/old': {
      id: '/index/old'
      path: '/index/old'
      fullPath: '/index/old'
      preLoaderRoute: typeof IndexOldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flavors/$slug': {
      id: '/flavors/$slug'
      path: '/$slug'
      fullPath: '/flavors/$slug'
      preLoaderRoute: typeof FlavorsSlugRouteImport
      parentRoute: typeof FlavorsRoute
    }
  }
}

interface FlavorsRouteChildren {
  FlavorsSlugRoute: typeof FlavorsSlugRoute
}

const FlavorsRouteChildren: FlavorsRouteChildren = {
  FlavorsSlugRoute: FlavorsSlugRoute,
}

const FlavorsRouteWithChildren =
  FlavorsRoute._addFileChildren(FlavorsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FlavorsRoute: FlavorsRouteWithChildren,
  GiftRoute: GiftRoute,
  OrderRoute: OrderRoute,
  StoryRoute: StoryRoute,
  IndexOldRoute: IndexOldRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
